insert into equipa values
('Farense', 'POR'),
('Portimonense', 'POR'),
('Famalicão', 'POR'),
('Gil Vicente', 'POR'),
('Moreirense', 'POR'),
('Sporting de Braga', 'POR'),
('Vitória', 'POR'),
('Belenenses SAD', 'POR'),
('Benfica', 'POR'),
('Sporting', 'POR'),
('Marítimo', 'POR'),
('Nacional', 'POR'),
('Santa Clara', 'POR'),
('Boavista', 'POR'),
('Paços de Ferreira', 'POR'),
('Porto', 'POR'),
('Rio Ave', 'POR'),
('Tondela', 'POR'),
('Arouca', 'POR'),
('Feirense', 'POR'),
('Oliveirense', 'POR'),
('Vizela', 'POR'),
('Sporting da Covilhã', 'POR'),
('Académica OAF', 'POR'),
('Benfica B', 'POR'),
('Casa Pia', 'POR'),
('Estoril Praia', 'POR'),
('Mafra', 'POR'),
('Vilafranquense', 'POR'),
('Leixões', 'POR'),
('Penafiel', 'POR'),
('Porto B', 'POR'),
('Varzim', 'POR'),
('Cova da Piedade', 'POR'),
('Chaves', 'POR'),
('Académico de Viseu', 'POR'),
('Real Madrid', 'ESP'),
('Milan', 'ITA'),
('Bayern de Munique', 'GER'),
('Liverpool', 'ENG'),
('Barcelona', 'ESP'),
('Ajax', 'NED'),
('Manchester United', 'ENG'),
('Internazionale', 'ITA'),
('Juventus', 'ITA'),
('Nottingham Forest', 'ENG'),
('Celtic', 'SCO'),
('Hamburgo', 'GER'),
('Steaua Bucareste', 'ROU'),
('Olympique de Marseille', 'FRA'),
('Borussia Dortmund', 'GER'),
('Chelsea', 'ENG'),
('Feyenoord', 'NED'),
('Aston Villa', 'ENG'),
('PSV Eindhoven', 'NED'),
('Estrela Vermelha', 'SRB'),
('Atlético de Madrid', 'ESP'),
('Stade de Reims', 'FRA'),
('Valencia', 'ESP'),
('Eintracht Frankfurt', 'GER'),
('Partizan', 'SRB'),
('Panathinaikos', 'GRE'),
('Leeds United', 'ENG'),
('Saint Etienne', 'FRA'),
('Borussia Mönchengladbach', 'GER'),
('Brugge', 'BEL'),
('Malmö', 'SWE'),
('Roma', 'ITA'),
('Sampdoria', 'ITA'),
('Bayer Leverkusen', 'GER'),
('Monaco', 'FRA'),
('Arsenal', 'ENG'),
('Tottenham', 'ENG'),
('Paris Saint‐Germain', 'FRA');
